---
# Install build environment for MakeMKV
# Just pick based on the OS family
- name: "Prepare Build Environment on {{ ansible_os_family }}"
  include_tasks: "devtools-{{ ansible_os_family }}.yaml"

- name: "Install tools for ffmpeg build on {{ ansible_os_family }}"
  include_tasks: "ffmpeg-{{ ansible_os_family }}.yaml"
