# Create a build environment and build MakeMKV CLI
#
#
- name: MakeMKV cli
  hosts: localhost
  connection: local

  vars:
    makemkv:
      version: 1.18.4
      components:
        - oss
        - bin

  tasks:
    - name: Say Hello
      debug:
        msg: Hello

    # ---------------------------------------------------
    # Right now this playbook will only work in a toolbox
    # This protects the base OS from contamination
    # ---------------------------------------------------
    - name: Check Toolbox
      block:
        - name: Run only in toolbox
          stat:
            path: /run/.toolboxenv
          register: in_toolbox

        - name: Fail if not running in toolbox
          fail:
            msg: Not running in toolbox
          when: in_toolbox.stat.exists == false

    # -------------------------------------------------
    # Preparation of the build environment requires root
    # It installs packages into the toolkit
    # -------------------------------------------------
    - name: Check Root Access (needed for package installation)
      block:
        - name: Test Sudo Access
          debug:
            msg: This command runs successfully under sudo
          become: true
          register: sudo_successful

    # ------------------------------------------------
    # Build requires compilers and other build tools to
    # Create the 'variable' binaries and libraries
    # One of the packages comes from RPM Fusion, so that
    # repo is enabled as well
    # ------------------------------------------------
    - name: Create build environment
      block:
        - name: Install Development Tools
          dnf5:
            name: "@Development Tools"
            state: present
          become: true
          
        - name: Install required packages from fedora repos
          dnf5:
            name:
              - openssl-devel
              - expat-devel
              - mesa-libGL-devel
              - qt5-qtbase-devel
              - zlib-devel
              - distribution-gpg-keys
            state: present
          become: true
  
        - name: Import RPM Fusion Free GPG Key (from distribution-gpg-keys)
          rpm_key:
            state: present
            key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_version }}

        - name: Enable the RPM Fusion repository
          dnf5:
            name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
            state: present
          become: true
          when: ansible_distribution == 'Fedora'      
            
        - name: Install ffmpeg packages from RPM Fusion
          dnf5:
            name:
              - ffmpeg-devel
            state: present
          become: true

    # ------------------------------------------------------------
    # MakeMKV is build on Linux from two source tarballs
    # One of those has compilable sources to build libraries and
    # two binaries for the app
    # The second has a single relocatable binary of what
    # look like a Java jar file and auxiliary files. These latter
    # are just placed into the destination host without alteration
    # ------------------------------------------------------------
    - name: Get MakeMKV Sources
      block:
        - name: Get MakeMKV Tarballs
          uri:
            url: "https://www.makemkv.com/download/makemkv-{{ item }}-{{ makemkv.version }}.tar.gz"
            dest: "{{ ansible_env.PWD }}/makemkv-{{ item }}-{{ makemkv.version }}.tar.gz"
            creates: "{{ ansible_env.PWD }}/makemkv-{{ item }}-{{ makemkv.version }}.tar.gz"
          loop: "{{ makemkv.components }}"

        - name: Create Destination for unpack
          file:
            name: src
            state: directory
            
        - name: Unpack MakeMKV Tarballs
          unarchive:
             src: "{{ ansible_env.PWD }}/makemkv-bin-{{ makemkv.version }}.tar.gz"
             dest: "{{ ansible_env.PWD }}/src"
             extra_opts: [ "--strip-components", '1' ]

        - name: Save the BIN makefile (we don't need it, but hey)
          copy:
            src: src/Makefile
            dest: src/Makefile.bin

        - name: Unpack MakeMKV Tarballs
          unarchive:
             src: "{{ ansible_env.PWD }}/makemkv-oss-{{ makemkv.version }}.tar.gz"
             dest: "{{ ansible_env.PWD }}/src"
             extra_opts: [ "--strip-components", '1' ]
          
      tags: tarballs

    # -----------------------------------------------------------------------
    # This block just runs the configure and make commands for the 
    # compiled components of MakeMKV.  This process does not build
    # the GUI parts of MakeMKV so it can run in a container without a display
    # -----------------------------------------------------------------------
    - name: Build Components
      block:
        - name: Configure Source Build
          shell:
            chdir: "{{ ansible_env.PWD }}/src"
            cmd: ./configure --disable-gui
            creates: "{{ ansible_env.PWD }}/src/config.log"

        - name : Build MakeMKV linux files
          make:
            chdir: "{{ ansible_env.PWD }}/src"
            
      tags: build

    # -----------------------------------------------------------
    # The container is built from scratch. It contains only files
    # that are require to run the app, and none of the build only
    # artifacts will be present. These steps create the model file
    # tree that will eventually be placed into the container image.
    # -----------------------------------------------------------
    - name: Populate Model Tree
      block:
        #
        # files from src/out
        #
        - name: Copy compiled binaries
          copy:
            src: "src/out/{{ item }}"
            dest: "model/usr/bin/{{ item }}"
            mode: 0755
          loop:
            - mmccextr
            - mmgplsrv

        # NOTE: Add arch for other systems. Assuming x86_64 (amd64)
        - name: Copy portable binary
          copy:
            src: "src/bin/amd64/{{ item }}"
            dest: "model/usr/bin/{{ item }}"
            mode: 0755
          loop:
            - makemkvcon

        - name: Copy Libraries
          copy:
            src: "src/out/{{ item }}"
            dest: "model/usr/lib64/{{ item }}"
            mode: 0644
          loop:
            - libdriveio.so.0
            - libmakemkv.so.1
            - libmmbd.so.0
            
        - name: Copy Shared FIles
          copy:
            src: "src/src/share/{{ item }}"
            dest: "model/usr/share/MakeMKV/{{ item }}"
            mode: 0644
          loop:
            - appdata.tar
            - blues.jar
            - blues.policy

      tags: model


    # -----------------------------------------------------------
    # 
    # -----------------------------------------------------------
    - name: Resolve linking dependencies
      block:
        - name: Identify dynamically linked binaries
          shell:
            cmd: "find model | xargs file | grep executable | cut -d: -f1"
          register: exec_search

        - name: Record the list of dynamically linked executables
          set_fact:
            executables: "{{ exec_search.stdout_lines }}"

        - name: Report files found
          debug:
            msg: "{{ executables }}"


      tags: dependencies
