---
#
# Install build tools on a Debian or RedHat family system
#
- name: Build ffmpeg for static linking
  hosts: localhost
  connection: local

  vars_files:
    - makemkv.yaml

  roles:
    - build-ffmpeg
