---
#
# Install build tools on a Debian or RedHat family system
#
- name: Build ffmpeg for static linking
  hosts: localhost
  connection: local

  vars:
    ffmpeg:
      version: 8.1

  tasks:
    - name: Clone ffmpeg repository
      git:
        repo: https://git.ffmpeg.org/ffmpeg.git
        version: "release/{{ ffmpeg.version }}"
        clone: true
        single_branch: true
        dest: "{{ ansible_env.PWD }}/build/ffmpeg"

    - name: Configure ffmpeg
      shell:
        cmd: |
          ./configure \
          --prefix={{ ansible_env.PWD }}/build/usr \
          --enable-static \
          --disable-shared \
          --enable-pic \
          --enable-libfdk-aac
        chdir: "{{ ansible_env.PWD }}/build/ffmpeg"
        creates: "{{ ansible_env.PWD }}/build/ffmpeg/config.h"

    - name: Build ffmpeg
      shell:
        cmd: make
        chdir: "{{ ansible_env.PWD }}/build/ffmpeg"
        creates: "{{ ansible_env.PWD }}/build/ffmpeg/ffmpeg"

    - name: Install ffmpeg
      shell:
        cmd: make install
        chdir: "{{ ansible_env.PWD }}/build/ffmpeg"
        creates: "{{ ansible_env.PWD }}/build/usr/bin/ffmpeg"
