---
#
# Install build tools on a Debian or RedHat family system
#
- name: Prepare Build Environment
  hosts: localhost
  connection: local

  vars_files:
    - makemkv.yaml

  roles:
    - builder-env
