---
#
# Install build tools on a Debian or RedHat family system
#
- name: Prepare Build Environment
  hosts: localhost
  connection: local

  vars:
    makemkv:
      version: 2.0.0
    ffmpeg:
      version: 9.0

  roles:
    - build-makemkvcon
