---
#
# Install build tools on a Debian or RedHat family system
#
- name: Prepare Build Environment
  hosts: localhost
  connection: local

  vars:
    makemkv:
      version: 1.18.4
    ffmpeg:
      version: 8.1

  roles:
    - container-builder
