---
# Install build environment for MakeMKV
- name: "Prepare Build Environment on {{ ansible_os_family }}"
  include_tasks: "devtools-{{ ansible_os_family }}.yaml"

- name: "Build ffmpeg"
  import_tasks: "ffmpeg.yaml"
  tags: ffmpeg

- name: "Create a place for building stuff"
  file:
    path: "{{ ansible_env.PWD }}/build/unpack"
    state: directory
    recurse: true

- name: Unpack MakeMKV Tarballs
  unarchive:
#    src: "{{ ansible_env.PWD }}/build/tarballs/makemkv-{{ item }}-{{ makemkv.version }}.tar.gz"
    src: "https://www.makemkv.com/download/makemkv-{{ item }}-{{ makemkv.version }}.tar.gz"
    dest: "{{ ansible_env.PWD }}/build/unpack/"
    remote_src: true
  loop:
    - oss
    - bin

  tags: unpack

# -----------------------------------------------------------------------
# This block just runs the configure and make commands for the 
# compiled components of MakeMKV.  This process does not build
# the GUI parts of MakeMKV so it can run in a container without a display
# -----------------------------------------------------------------------
- name: Build Components
  block:
    - name: Configure Source Build
      shell:
        chdir: "{{ ansible_env.PWD }}/build/unpack/makemkv-oss-{{ makemkv.version }}"
        cmd: "PKG_CONFIG_PATH={{ ansible_env.PWD }}/usr/lib ./configure --disable-gui"
        creates: "config.log"

    - name: Create space for EULA
      file:
        path: "{{ ansible_env.PWD }}/build/unpack/makemkv-{{ item }}-{{ makemkv.version }}/tmp"
        state: directory
      loop:
        - oss
        - bin

    - name: Build MakeMKV linux files
      make:
        chdir: "{{ ansible_env.PWD }}/build/unpack/makemkv-oss-{{ makemkv.version }}"
            
    - name: Accept EULA License
      copy:
        dest: "{{ ansible_env.PWD }}/build/unpack/makemkv-{{ item }}-{{ makemkv.version }}/tmp/eula_accepted"
        content: |
          accepted
      loop:
        - oss
        - bin

  tags: build

- name: Create Model
  block:
    - name: Create model directory for container tree
      file:
        path: "{{ ansible_env.PWD }}/model"
        state: directory

    - name: Install built files into model
      make:
        target: install
        params:
          DESTDIR: "{{ ansible_env.PWD }}/model"
          PREFIX: "/usr"
        chdir: "{{ ansible_env.PWD }}/build/unpack/makemkv-{{ item }}-{{ makemkv.version }}"
      loop:
        - oss
        - bin

  tags: model
