---
# Install tools for RedHat family systems
- name: Install Development Tools
  dnf:
    name: "@Development Tools"
    state: present
  become: true
          
- name: Install required packages from fedora repos
  dnf:
    name:
      - nasm
      - openssl-devel
      - expat-devel
      - mesa-libGL-devel
      - qt5-qtbase-devel
      - zlib-devel
      - distribution-gpg-keys
    state: present
  become: true
  
- name: Import RPM Fusion Free GPG Key (from distribution-gpg-keys)
  rpm_key:
    state: present
    key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-{{ item }}-fedora-{{ ansible_distribution_version }}"
  become: true
  loop:
    - free
    - nonfree

- name: Enable the RPM Fusion repositories
  dnf5:
    name: "https://download1.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ ansible_distribution_version }}.noarch.rpm"
    state: present
  become: true
  when: ansible_distribution == 'Fedora'
  loop:
    - free
    - nonfree
              
- name: Install ffmpeg packages from RPM Fusion
  dnf5:
    name:
      - fdk-aac
#      - ffmpeg-devel
    state: present
  become: true

- name: Clean DNF5 Cache -  RPM fusion in cache causes problems
  shell:
    cmd: "dnf clean packages"
  become: true
