---
# Install tools for Debian family systems
- name: Install Build Tools
  apt:
    name:
      - build-esssentials
      - pkg-config
    state: present
  become: true

- name: Install Libraries for makemkv
  apt:
    name:
      - libc6-dev \
      - libssl-dev \
      - libexpat1-dev \
      - libavcodec-dev \
      - libgl1-mesa-dev \
      - qtbase5-dev \
      - zlib1g-dev
    state: present
  become: true

