---
name: build-makemkvcon
run-name: Build MakeMKV CLI Software Container
on: [ workflow_dispatch ]

# variables
env:
  MAKEMKV_VERSION: 1.18.4
  FFMPEG_BRANCH: release/8.1

  AUTHOR: Mark Lamourine <mark@llamatek.dev>
  BUILDER: Mark Lamourine <mark@llamatek.dev>
  
  IMAGE_NAME: makemkvcon
  IMAGE_TAGS: latest #${{ github.sha }}

  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
#  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone workspace for makemkv-container
        uses: actions/checkout@v7

      - name: Install Ansible and prerequisite tools
        run: |
          scripts/prep-debian.sh

      - name: Prepare build environment
        run: |
          ansible-playbook prepare-build-env-pb.yaml
