---
name: build-makemkvcon
run-name: Build MakeMKV CLI Software Container
on: [ workflow_dispatch ]

# variables
# makemkv:
#   version: 1.18.4
#   components:
#     - oss
#     - bin

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Tools
        run: |
          sudo apt-get install \
            build-essential \
            pkg-config \
            libc6-dev \
            libssl-dev \
            libexpat1-dev \
            libavcodec-dev \
            libgl1-mesa-dev \
            qtbase5-dev \
            zlib1g-dev

      - name: Clone ffmpeg repo
        run: git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg

      - name: Configure ffmpeg
        working_directory: ffmpeg
        run:
          ./configure \
            --prefix=/tmp/ffmpeg \
            --enable-static \
            --disable-shared \
            --enable-pic \
            --enable-libfdk-aac

      - name: Build ffmpeg
        working_directory: ffmpeg
        run: make install
    
